version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"  # Make sure this is set correctly
    volumes:
      - uploads:/app/uploads  # Mount your upload directory
      - temp:/app/temp  # Mount your temp directory
volumes:
  uploads:
  temp:
